#! /bin/sh

xrdb ~/.Xresources &
killall polybar 
killall redshift
xsetroot -cursor_name left_ptr &

bspc config top_padding        0
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       0
bspc config window_gap         30

# Borders and gaps
bspc config borderless_monocle true
bspc config gapless_monocle true

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#AF865A"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# It looks like these options get overridden by Compton...
bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true

# Misc
bspc config split_ratio 0.50
bspc config auto_alternate true
bspc config auto_cancel true
bspc config initial_polarity second_child

# Set up displays
bspc monitor eDP-1 -d 1 2 3 4 5
#bspc monitor -d HDMI-1 6 7 8

# startup
# mpv --loop --wid=0 ~/Downloads/d.gif
# dunst &
# feh-blur -d &
# udiskie &
# colorer -R
#$HOME/scripts/feh-blur -d &
#nm-applet &
#brightnessctl set 15 &
#nitrogen --restore &

sxhkd &
#~/.screenlayout/standard.sh &
wal -R &
~/.config/polybar/launch.sh --hack &
picom -b &
redshift -t 6500:3200 &

